services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    tty: true
    stdin_open: true
    networks:
      ccdc_network:
        ipv4_address: 10.8.0.5
    expose:
      - "22"
      - "80"
      - "443"
    cap_add:
      - NET_ADMIN

networks:
  ccdc_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1
